### ISSUE TITLE
Can't initialize new package with `pkg-utils init`

### ISSUE THREAD

**Issue by nkgentile** [sanity-io/pkg-utils#265]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Initialization prompt will error with:

```error Cannot find package 'prettier-plugin-packagejson' imported from [.]/noop.js```
(`[.]` is the absolute path to the current working directory)

**To Reproduce**

1. Run `npx @sanity/pkg-utils@latest init [path]` and answer prompts

**Expected behavior**

**Screenshots**

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**

`node@18.16.0`
`npm@9.5.1`

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by nkgentile** [comment]
Somehow related to https://github.com/prettier/prettier/issues/15085

**Comment by mariuslundgard** [comment]
Hey @nkgentile – this has been resolved as of v3.2.1 😌
