### ISSUE TITLE
Automatically add devDependencies to `bundledPackages`?

### ISSUE THREAD

**Issue by rexxars** [sanity-io/pkg-utils#967]
Opening this for a discussion, as I don't know the full impact it might have;

Currently, when you build a package that imports from a dev dependency, the contents gets bundled (inlined) automatically - but any type reference does not, still referencing the dev dependency. To work around this, you can add the dev dependency to `bundledPackages`, but this is a manual process.

Maybe we should either:
- Throw an error/warning if you have not declared the dev dependency under `bundledPackages` (unless it is also listed as a peer dependency)
- Automatically _add_ the dev dependency to the `bundledPackages` array

**Comment by stipsan** [comment]
It should definitely automatically add it to `bundledPackages` 👍 I'll work on this when I'm back on Monday, it's a small and quick change 😄
